#!/usr/bin/with-contenv bash
# shellcheck shell=bash

set -o errexit -o nounset -o pipefail

echo "[INFO] Starting dnsdist..."

exec 2>&1
exec /usr/bin/dnsdist --supervised --disable-syslog --config /config/dnsdist.conf
